### PR TITLE
Feature/remove any references to ges disc servers from the meditor codebase

### PR DESCRIPTION
**Pull request by KrupaRami**
This PR contains removal of references to GES DISC servers and people from codebase to support open sourcing meditor. Changes are as follows,
- removed references to GES DISC, GESDISC, etc.
- removed references to "lb.gesdisc.eosdis.nasa.gov/meditor"
- added "fake" people emails in test files to remove references to GES DISC people.
- Added relative URLs in replace of default LB in .env files

### CODE REVIEW

**Comment by benforshey** [comment]
Hey, I really like the idea behind this PR—especially when it comes to our fixtures! There are a few places where I still have questions:
- Sometimes we remove "GES DISC" but leave a @nasa.gov email next to it. Should we remove both?
- Sometimes, like for OpenGraph (used in our `<meta property="og:url" >`), [a relative URL won't work](https://indieweb.org/The-Open-Graph-protocol#Disallows_relative_URLs). Maybe we can use an environment variable instead?
- I'm not sure where the NB Viewer parses URLs (Node or Browser), but I know that some Node URL parsers don't handle relative URLs. We could either be careful to test these cases, or maybe we could use an environment variable there, too.

**Comment by KrupaRami** [comment]
Hey, I like the idea of using environment variables. I have kept @nasa.gov because we will still use meditor for any NASA website even after open sourcing it but it is using fake users. Do you want to discuss about using environment variables sometime today?

**Comment by benforshey** [comment]
> Hey, I like the idea of using environment variables. I have kept @nasa.gov because we will still use meditor for any NASA website even after open sourcing it but it is using fake users. Do you want to discuss about using environment variables sometime today?

Cool, let's discuss! See you on Gather. 👍🏼 

Just to clarify about the email addresses, I'm great with hashbrowns@nasa.gov, but was wondering if we should also change real email addresses like gsfc-nasa-disc.

**Review by joncarlson — APPROVED** [review]
This is great Krupa! Thanks for getting all these changed. This was the last step for the open source epic :)

**Pull request merged**
